let complimentsnotesArr = [
	["amazing", "すごい"],
	["wonderful", "素晴らしい  (すばらしい)"],
	["cute", "かわいい"],
	["popular", "人気な  (にんきな)"],
	["outfit", "服　（ふく）"],
	["cooking", "料理  (りょうり)"],
	["driving", "運転  (うんてん)"],
	["smart", "頭がいい  (あたまがいい)"],
	["genius", "天才  (てんさい)"],
	["cheap", "安い  (やすい)"],
	["flattery", "お世辞  (おせじ)"],
	["to be popular", "モテる"],
	["to be troubled", "困る  (こまる)"],
	["to respect", "尊敬する (そんけいする)"],
	["to be reliable", "頼りになる  (たよりになる)"],
	["to rely on", "頼りにする  (たよりにする)"],
	["to compliment", "褒めて  (ほめて)"],
	["to shine", "照る  (てる)"],
	["too much ~", "~すぎる"],
	["amazingly, super", "すごく"],
	["lovely person", "素敵な人  (すてきなひと)"],
	["as expected", "さすが"],
	["beautiful woman", "綺麗な女の人  (きれいなおんなのひと)"],
	["really cute", "本当にかわいい"],
	["kinda, somewhat", "なんか"],
	["not at all", "全然  (ぜんぜん)"],
	["You are cuter than me", "(you/name)のほうがかわいいよ"],
	["cool, handsome, good-looking", "かっこいい"],
	["cool car", "かっこいい車ですね"],
	["hot guy, good-looking man", "イケメン"],
	["dope, fashionable", "イケてる"],
	["You look like a model", "モデル見たい"],
	["You've gotta be popular, right?", "モテるでしょう"],
	["am i right?", "でしょう"],
	["That outfit looks good on you", "その服似合ってる"],
	["trendy, fashionable", "おしゃれ"],
	["trendy cafe", "おしゃれなカッフェ"],
	["good skill", "上手  (じょうず)"],
	["Misa English is good", "みさの英露, じょうず"],
	["You're great at cooking", "料理上手ですね"],
	["to fall in love", "惚れる  (ほれる)"],
	["can't help it", "~ちゃう"],
	["can'y help but fall in love", "惚れちゃう"],
	["easy to...(verb)", "(verb stem) + やすい"],
	["You're easy to talk to", "話しやすい"],
	["compliment me more", "もっと褒めて"],
	["to get carried away", "調子に乗る  (ちょうしにのる)"],
	["to get embarrased", "照れる  (てれる)"],
	["You're making me blush", "ああ、照れるじゃん"],
	["Geez, stop it... but actually don't stop", "もうやめてよ。。。でもやめないで"],
	["Flattery won't get you anywhere", "そんなに褒めても、何も出ないよ"],
	["You're quite the flatterer", "お世辞が上手ですね"],
	["No, you really are beautiful", "いや、本当に綺麗ですよ"],
	["You're just flattering me right?", "おせじでしょう"],
	["Even if its an empty compliment, I'm still happy", "お世辞でも、うれしい"],
	["I'm really tired", "すごく疲れた  (つかれた)"],
	["I'm in trouble", "困ってる"],
	["It suits you well", "似合ってる (にあってる)"],
	["I'm happy", "うれしい"],
	["I know", "知ってる  (sarcastically)"],
	["It's not an empty compliment", "おせじじゃないですよ"],
	["I mean it", "いや、本当に"]
];
