let havetonotesArr = [
	["everyone", "みんな"],
	["perfect", "完璧な (かんぺきな)"],
	["big", "大きい（おおきい）"],
	["to wake up", "起きる　（おきる）"],
	["have to do {}", "{} なきゃ, {} なければいけません"],
	["may do something", "てもいい"],
	["May I come in?", "入ってもいい"],
	["even if", "ても"],
	["don't have to", "なくてもいい"],
	["You may eat", "食べてもいいですよ"],
	["Do I have to watch?", "見なければいけませんか？"],
	["You don't have to eat everything", "全部たべなくてもいいですよ"],
	["You don't have to eat if you don't like it", "好きじゃなあいなら食べなくてもいいよ"],
	["You don't have to say it", "言わなくてもいいよ"],
	["You don't have to tell me if you don't want to", "言いたくないなら言わなくてもいいよ"],
	["You don't have to talk about it", "話さなくてもいい"],
	["about {}", "{} について"],
	["approximately, about, around", "ぐらい"],
	["about 5 minutes", "五分ぐらい"],
	["book about love", "愛についての本"],
	["to talk about the news", "ニューすについて話す"],
	["that matter, thing", "その事"],
	["physical thing, object", "物"],
	["thing, action, event", "事"],
	["about that thing", "その事について"],
	["You don't have to talk about that", "その事について話さなくてもいいよ"],
	["don't have to wake up", "起きなくてもいい"],
	["early tomorrow", "明日早く"],
	["You don't have to do it", "しなくてもいいよ"],
	["You don't have to wait for me", "私のことを待たなくてもいいよ"],
	["not stand", "立たない"],
	["You don't have to stand up", "立たなくてもいい"],
	["You don't have to understand everything", "全部わからなくても大丈夫だよ"],
	["not perfect", "かんぺきじゃない"],
	["The hotel room doesn't have to be big", "ホテルの部屋は大きくなくてもいい"],
	["I don't have to eat", "食べなくてもいい"],
	["I don't have to watch", "見なくてもいい"],
	["I have to watch", "見なきゃ"],
	["I read about {}", "{} について読んだ"],
	["I don't have to wake up early tomorrow", "明日早く起きなくてもいい"],
	["I have to study", "勉強しなきゃ"],
	["It doesn't have to be perfect", "完璧じゃなくてもいい"],
	["It doesn't have to be big", "大きくなくてもいい"]
];
