let ifnaranotesArr = [
	["want", "欲しい （ほしい）"],
	["child", "子供　（こども）"],
	["kouhai", "後輩　（こうはい）"],
	["senpai", "先輩　（せんぱい）"],
	["song", "曲　（きょく）"],
	["headache", "頭が痛い　（あたまがいたい）"],
	["medicine", "薬　（くすり）"],
	["transfer", "乗り換え　（のりかえ）"],
	["outside", "外　（そと）"],
	["phone", "携帯　（けいたい）"],
	["squid", "イカ"],
	["to get married", "結婚する　（けっこんする）"],
	["to say so", "そう言う"],
	["to quit", "やめる"],
	["to lose", "負ける　（まける）"],
	["to practice", "練習する （れんしゅうする)"],
	["want {something}", "{something} が欲しい"],
	["if you want a child", "子供を欲しいなら"],
	["you have to get married", "結婚しなきゃ"],
	["you have to get married", "結婚しなければいけません"],
	["bad not do to ~", "~ければいけません"],
	["strong willed you have to", "しなきゃだめだ"],
	["fluent in Japanese", "日本語がペラペラになら"],
	["must be {something}", "{something} はず"],
	["meant to {verb}", "{verb} はず"],
	["planning to {verb}", "{verb} つもり"],
	["it rains", "雨が降る　（あめがふる）"],
	["Given that it will rain tomorrow, we shouldn't go for a picnic", "明日雨が降るなら、ピクニックに行かないほうがいい"],
	["should {verb}", "{verb た} ほうがいい"],
	["shouldn't {verb}", "{verb ない} ほうがいい"],
	["maybe I will {do something}", "{lets form verb} かな"],
	["indirectly explaining", "{} んですが or んですけど"],
	["if you don't want to lose", "負けたくないなら"],
	["to become strong", "強くなる"],
	["have to become strong", "強くならなきゃ"],
	["to improve one's skill", "上手になる"],
	["you have to practice more", "もっと練習しなきゃ"],
	["if you want to improve your Japanese", "日本語が上手になりたいなら、もっと練習しなきゃ"],
	["{noun} but not...", "{noun} なら"],
	["You can do it! (not others)", "みさならできる"],
	["If I go to Japan, I'll buy a camera first", "日本にいくなら、まずカメラを買う"],
	["If you want a child, you have to get married first", "子供が欲しいなら、結婚しなきゃだめだ"],
	["If I live in Japan, I'll be fluent in Japanese", "日本に住んだら、日本語がペラペラになる"],
	["If I want to work in Japan, I have to study Japanese", "日本で働きたいなら, 日本語を勉強しなきゃ"],
	["If you say so, senpai", "先輩がそう言うなら"],
	["If you say so, senpai, I'll goo, too", "先輩そう言うなら、私も行きます"],
	["If my senpai likes it, this song must be awesome", "先輩が好きなら、この曲はすごいはず"],
	["If senpai quits smoking, I'll quit, too", "先輩がタバコをやめるなら、私もタバコをやめる"],
	["I plan on having a picnic tomorrow", "明日ピクニックにいくつもり"],
	["If it hurts, you should take medicine", "痛いなら、薬を飲んだほうがいい"],
	["I'm lost", "迷っちゃいました"],
	["If you want to go to Shibuya station, transfer to the Yamanote Line", "渋谷駅に行きたいなら、JR山手線に乗り換えてください"],
	["If you will use the phone, please go outside", "携帯を使うなら、外に出ってください"],
	["If you don't want to lose, you have to become strong", "負けたくないなら、強くならなきゃ"],
	["If you want to improve your Japanese, you have to practice more", "日本語が上手になりたいなら、もっと練習しなきゃ"],
	["I like squid but not...", "イカなら好きです"],
	["I have a dog but not...", "犬を飼っています"],
	["I have been to Kyoto but not...", "京都なら行ったことがあります"],
	["I can speak for 5 minutes but not longer", "五分なら話せます"]
];
