let iftaranotesArr = [
	["stomach", "お腹"],
	["become", "なる"],
	["nose", "鼻　（はな）"],
	["again", "また"],
	["police", "警察　（けいさつ）"],
	["accident", "事故　（じこ）"],
	["question", "質問　（しつもん）"],
	["girlfriend", "彼女　（かのじょ）"],
	["quiet", "静かな　（しずかな）"],
	["to get nervous", "緊張する　（きんちょうする）"],
	["to appear", "現れる　（あわられる）"],
	["touch it", "触って　（さわって）"],
	["to be sunny", "晴れる　（はれた）"],
	["to tell a lie", " 嘘をつく　（うそをつく）"],
	["to forgive", "許す　（ゆるす）"],
	["to kill", "殺す　（ころす）"],
	["to drive", "運転する"],
	["to cause", "起こす"],
	["to ask", "聞く"],
	["to fail", "失敗する　（しっぱいする）"],
	["drink milk", "牛乳を飲む"],
	["my stomach (always) hurts when(ever) I drink milk", "牛乳を飲むと、お腹が痛くなる"],
	["my stomach hurts whenever I eat curry", "カレーを食べると、お腹が痛くなる"],
	["to eat too much", "食べすぎる"],
	["to drink too much", "飲みすぎる"],
	["when I get nervous", "緊張すると"],
	["cannot speak", "話せない"],
	["if I don't eat, I get hungry", "食べないと、お腹が空く"],
	["if I don't wear glasses, I can't see anything", "眼鏡をかけないと、何も見えない"],
	["if I don't rest, I make a mistake", "休まないと、間違えちゃうよ"],
	["double click", "ダバルクリックをする"],
	["open a file", "ファイルを開く　（ファイルをひらく）"],
	["if you don't double-click, you can't open the file", "だバルクリックをしない、ファイルが開けないよ"],
	["when I rubbed the lamp", "ランプをこすると"],
	["Genie appeared", "ジーニーが現れた"],
	["instead of {}", "{} の代わりに　（のかわりに）"],
	["She said cock instead of coke", "cokeの代わりにcockと言った"],
	["When I said 'coke' instead of 'cock', my friends laughed at me", "cokeの代わりにcockと言ったら, 友達に笑われた"],
	["sit down", "座って　（すわって）"],
	["if it's sunny", "晴れたら"],
	["to grow, extend", "伸びる　（のびる）"],
	["when Pinocchio lies, his nose grows", "ピノキオは嘘をつくと、鼻が伸びる"],
	["to call someone", "に電話する"],
	["driving license", "運転免許　（うんてんめんきょ）"],
	["drive a car", "車を運転する"],
	["ask me anything", "何でも聞いてください"],
	["to bring someone", "連れて来る　（つれてくる）"],
	["to bring an object", "持って来る　（もってくる）"],
	["What if {}", "{} たら、どうする？"],
	["if its pizza", "ピツァだったら"],
	["if it's quiet", "静かだたら"],
	["if it's hot", "暑かったら"],
	["if it's interesting", "面白かったら"],
	["don't go", "行かない"],
	["didn't go", "いかなかった"],
	["to make it on time", "間に合う　（まにあう）"],
	["without me", "先に　（さきに）"],
	["I feel energetic when I eat curry", "カレーを食べると、元気になる"],
	["I broke my phone", "携帯をこわしちゃた （けいたいをこわしちゃた）"],
	["I get fat (and I'm not happy about it)", "太っちゃう"],
	["I become sick when I drink alcohol", "お酒を飲みすぎると、気持ち悪くなる"],
	["I can't speak Japanese when I get nervous", "緊張すると、日本語を話せなくなる"],
	["I make a mistake (and I don't like it)", "間違えちゃう"],
	["I said {}", "{} と言いた"],
	["I was laughed at by my friends", "友達に笑われた　（ともだちにわらわれた）"],
	["If it's sunny tomorrow, let's have a picnic", "明日晴れたら、ピクニくしましょう"],
	["If you kill that man I will call the police", "その人を殺したら、警察に電話する"],
	["If I drive", "運転したら"],
	["If I drive, I will cause an accident", "運転したら、事故を起こすと思う"],
	["I have a question", "質問がある"],
	["If you have a question, ask me anything", "質問があったら、何でも聞いてください"],
	["If I had money", "お金があったら"],
	["If I had time", "時間があったら"],
	["If I had a girlfriend, I would bring her to this restaurant", "彼女がいたら、このレストランに連れてくる"],
	["If I don't make it", "間に合わなかったら"],
	["If I don't make it, go without me", "間に合わなかったら、先に行ってね"]
];
