let inordertonotesArr = [
	["library", "図書館　（としょかん）"],
	["dinner", "晩御飯　（ばんごはん）"],
	["clothes", "服　（ふく）"],
	["to lose weight", "痩せる　（やせる）"],
	["to exercise", "運動する　（うんどうする）"],
	["to return {}", "{}を返す　（かえす）"],
	["to climb", "登る　（のぼる）"],
	["to help", "手伝う　（てつだう）"],
	["in order to lose weight", "痩せるために"],
	["in order to read books", "本を読むために"],
	["for my girlfriend", "彼女のため"],
	["have to go", "行かなきゃ"],
	["to go to return a book", "本を返しに行く"],
	["after work", "仕事のあと"],
	["after work I'm going to drink at an Izakaya", "仕事の後居酒屋に飲みに行く"],
	["to climb Mt. Fuji", "富士山に登る"],
	["to meet a friend", "友達に会う"],
	["to save someone", "someoneを助ける （たすける）"],
	["Spiderman went to save his girlfriend", "スパイダーマンは彼女を助けに行った"],
	["I exercise everyday", "毎日運動する"],
	["I exercise everyday to lose weight", "痩せるために毎日運動する"],
	["I've been exercising everyday", "毎日運動している"],
	["I bought flowers for my girlfriend on valentines day", "バレンタインデーに彼のために花を買った"],
	["I will go to the library to borrow a book", "図書館に本をに借りにいく"],
	["I have to go to to the library to return a book", "図書館に本を返しに行かなきゃ"],
	["I will go to a restaurant to eat dinner with my friend", "レストランに友達と晩御飯を食べに行く"],
	["I want to go to Japan to climb Mt. Fuji", "日本に富士山に登りに行きたい"]
];
