let potentialformnotesArr = [
	["skillfully", "上手に"],
	["to sleep", "寝る"],
	["to wake up", "起きる"],
	["to open", "開ける"],
	["to speak", "話す"],
	["to listen", "聞く"],
	["to buy", "買う"],
	["to wait", "待つ"],
	["to hangout", "遊ぶ"],
	["to cook", "料理する"],
	["to practice", "練習する"],
	["to bring", "持って来る"],
	["thing, matter, event", "こと"],
	["scary thing to do", "怖いこと"],
	["can eat", "食べらる"],
	["can eat (formal)", "食べられます"],
	["cannot eat", "食べられない"],
	["couldn't eat", "食べられなかった"],
	["could eat", "食べられた"],
	["could eat (formal)", "食べられました"],
	["removing the ra", "ら抜き言葉 （らぬきことば）"],
	["can watch", "見られる"],
	["can see", "見える"],
	["cannot see a movie", "映画が見られえない"],
	["can sleep", "寝られる"],
	["can't sleep", "寝られない"],
	["can wake up", "起きられる"],
	["can't wake up", "起きられない"],
	["can't wake up early in the morning", "朝早く起きられない"],
	["when I was a student", "学生のとき"],
	["couldn't wake up", "起きられなかった"],
	["can open", "開けられる"],
	["cannot open the door", "ドアが開けられない"],
	["can write", "書ける"],
	["can go", "行ける"],
	["alone, on my own", "一人で"],
	["can listen", "聞ける"],
	["can hear", "聞こえる"],
	["can you hear me?", "聞こえますか？"],
	["can buy", "買える"],
	["can buy a new computer", "新しいパスこんが買えます"],
	["thanks to (person)", "(person) お陰で　（おかげで）"],
	["adults can drink alcohol", "大人はお酒が飲めます"],
	["can't drink alcohol", "お酒が飲めない"],
	["all you can eat", "食べ放題　（食べほうだい）"],
	["all you can drin", "飲み放題"],
	["let's go to an all you can eat restaurant", "食べ放題のレストランに行こう"],
	["can wait", "待てる"],
	["let's wait", "待とう"],
	["can't wait", "待てない"],
	["can hangout", "遊べる"],
	["next week I can't hangout", "来週は遊べない"],
	["can play tennis", "テニスできる"],
	["can cook", "料理できる"]
];
