let wishididnotesArr = [
	["window", "窓　（まど）"],
	["wings", "翼　（つばさ）"],
	["pronunciation", "発音　（はつおん）"],
	["lid", "蓋 (ふた)"],
	["plane", "飛行機　（ひこうき）"],
	["teeth", "歯　（は）"],
	["expelled", "退学　（たいがく）"],
	["secret", "秘密　（ひみつ）"],
	["to fly", "飛ぶ　（とぶ）"],
	["to improve", "よくになる"],
	["to ask", "聞く　（きく）"],
	["to brush teeth", "磨く　（みがく）"],
	["to tell", "教える　（おしえる）"],
	["to bring", "持ってくる　（持ってくる）"],
	["to be pregnant", "妊娠する"],
	["if its cute", "かわいければ"],
	["if its good", "よければ"],
	["if its quiet", "静かだったら"],
	["if I was a student", "学生だったら"],
	["How can I ~", "どうすれば、~"],
	["to become better", "上手になる"],
	["How can I improve my Japanese?", "どうすれば、日本語が上手になりますか"],
	["How can I improve my pronunciation?", "どうすれば、発音がよくになりますか"],
	["What do you think?", "どう思う？"],
	["What should I do?", "どうしよう？"],
	["How to ~", "どうやって ~"],
	["How do I open this lid?", "どうやってこの蓋を開ける?"],
	["that day", "あの日　（あのひ）"],
	["to confess love", "告白する"],
	["phone number", "電話番号　（でんわばんご）"],
	["big mouth", "口が軽い　（くちがかるい）"],
	["to tell a secret", "秘密を教える"],
	["what if (hypothetical) ~", "もし ~ たら、なら、ば"],
	["100 million yen", "一億円　（いちおくえん）"],
	["What would you do if you have had 100 million yen", "もし一億円あったら、どうする"],
	["What would you say if I'm pregnant?", "もし妊娠していたら、何て言う？"],
	["If its hot, please open the window", "暑ければ、窓を開けてください"],
	["If its cold, please close the window", "寒ければ、窓を閉めてください"],
	["If I had wings, I could fly", "翼があれば、飛べる"],
	["If I had money, I could buy a house", "お金があれば、家が買える"],
	["If I pass the exam, my mum will buy me a computer", "試験い受かれば、お母さんはパソコンを買ってくれる"],
	["If I studied more I would have done better", "もっと勉強すればよかった"],
	["I wish I studied more before the test", "テストの前に、もっと勉強すればよかった"],
	["I wish I did ~", "~ ばよかった"],
	["I wish I confessed my love to Achan that day", "あの日Aちゃんに告白すればよかった"],
	["I wish I asked for Achan's phone number", "Aちゃんの電話番号を聞けばよかった"],
	["I wish I ate before I got on the plane", "飛行機に乗る前に、食べればよかった"],
	["I wish I brushed my teeth", "歯を磨けばよかった"],
	["I wish came to the party with my friend", "友達とパーテイーに来ればよかった"],
	["I wish I didn't do ~", "~ なければよかった"],
	["I wish I didn't come to this party", "パーテイーに来なければよかった"],
	["If you don't come to school, you'll be expelled", "学校に来なければ、退学です"],
	["I wish I didn't tell ~", "~ 言わなければよかった"],
	["I wish I didn't tell my secret", "秘密を教えなければよかった"],
	["I bought a game but it was boring", "ゲームを買ったけど、つまなかった"],
	["I wish I didn't buy this game", "このげーむ買わなければよかった"],
	["I wish I brought my camera", "カメラを持ってくればよかった"]
];
